#!/usr/bin/env bash
# redirection /redirect_me
sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown $USER:$USER /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4? permanent; }' /etc/nginx/sites-available/default
sudo service nginx restart
